/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfm_lp_CBCPeer */

#ifndef _Included_jfm_lp_CBCPeer
#define _Included_jfm_lp_CBCPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfm_lp_CBCPeer
 * Method:    create
 * Signature: ([D[D[D[I[D[I[I[D[I[I[[C[[C)J
 */
JNIEXPORT jlong JNICALL Java_jfm_lp_CBCPeer_create
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jobjectArray, jobjectArray);

/*
 * Class:     jfm_lp_CBCPeer
 * Method:    setTermOut
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jfm_lp_CBCPeer_setTermOut
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jfm_lp_CBCPeer
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jfm_lp_CBCPeer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jfm_lp_CBCPeer
 * Method:    solveWithNewCoefficients
 * Signature: ([D[D[D[I[IJ)I
 */
JNIEXPORT jint JNICALL Java_jfm_lp_CBCPeer_solveWithNewCoefficients
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jintArray, jlong);

/*
 * Class:     jfm_lp_CBCPeer
 * Method:    solveWithNewProblem
 * Signature: ([D[D[D[I[D[I[I[D[I[I[[C[[CJ)I
 */
JNIEXPORT jint JNICALL Java_jfm_lp_CBCPeer_solveWithNewProblem
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jobjectArray, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
